name: twof
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Firebase dependencies
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  firebase_database: ^11.1.4
  firebase_storage: ^12.3.4
  cloud_firestore: ^5.4.4
  intl: ^0.17.0
  uuid: ^4.5.1
  shared_preferences: ^2.3.2
  workmanager: ^0.5.2
  flutter_local_notifications: ^17.2.4
  firebase_messaging: ^15.1.3
  google_api_availability: ^5.0.0
  file_picker: ^8.1.3
  flutter_colorpicker: ^1.1.0
  connectivity_plus: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true

  assets:
    - assets/
flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/appIcon.jpg"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/appIcon.jpg"
  web:
    generate: true
    image_path: "assets/appIcon.jpg"
    background_color: "#ffffff"
    theme_color: "#ffffff"
  windows:
    generate: true
    image_path: "assets/appIcon.jpg"
    icon_size: 48 # min: 48, max: 256, default: 48
  macos:
    generate: true
    image_path: "assets/appIcon.jpg"